#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
##    url: jdbc:mysql://www.partitioner.cn:3306/recruitment_analysis?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/sampledb?useUnicode=true&characterEncoding=UTF-8

server:
  port: 8888

spring:
  datasource:
    driverClassName: dm.jdbc.driver.DmDriver
    url: jdbc:dm://localhost:5234
    username: SYSDBA
    password: SYSDBA
    druid:
      url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driverClassName}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jhon.recruitmentanalysis.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl